### ISSUE TITLE
Holes are spawning in the corners randomly

### ISSUE THREAD

**Issue by JakesCode** [EglibibsUnited/FoPAssignment#61]

**Comment by JakesCode** [comment]
>=

**Comment by xFORMIDABL3x** [comment]
![muchbugmanywow](https://user-images.githubusercontent.com/36956533/37462933-7980305a-284b-11e8-9671-c38e41eb540c.PNG)

**Comment by JakesCode** [comment]
looks bad

**Comment by JakesCode** [comment]
* Seems to be happening only on Level 3
